### ISSUE TITLE
Are you following the pro version?

### ISSUE THREAD

**Issue by shmediaproductions** [LiCybora/NanoDefenderFirefox#166]
https://jspenguin2017.github.io/uBlockProtector/#announcements

I don't have an issue so I apologize for the disturbance, I just couldn't find a more appropriate forum to ask this question in. The descriptions suggest you're still incorporating new pushes to the chromium source and the site calls it an official port, so I'm wondering if this is gonna be a port of the 'pro version' or the 'standard version.' That's all, thanks!

**Comment by LiCybora** [comment]
Short answer: Yes.

Long answer: Yes, and the version hosted on GitHub in 15.0.0.180 has changed the name with Pro version. AMO version still in 15.0.0.177 because I still have not reviewed all rules. Once it update to version 15.0.0.180, it will rename with word 'Pro'.

@jspenguin2017 Once I updated and follow the version with 'Pro', may you also add the 'Pro' name in homepage so users know which one I am forking?

**Comment by jspenguin2017** [comment]
OK, I just updated the homepage.

**Comment by LiCybora** [comment]
Due to #167 , the answer will be now both yes and no. Yes because 'Pro' version is still available on GitHub host. No since some rules in "Pro" are not allowed on AMO (see #167).

The port on AMO will therefore neither 'standard' nor 'pro'. I will rename it as "Nano Defender Firefox" as I am planning to add browser-specific features, which does not exist in 'pro' or 'standard'. Most rules in 'Pro' are also in AMO except those are not allowed. The version hosted on GitHub will still be 'Pro' version.

Will update README later to clarify.

**Comment by shmediaproductions** [comment]
So if I wanted to get the most possible functionality on firefox, e.g. defuse the most possible anti-adblock systems, would I be better off downloading the pro version on github, or using the version hosted on AMO? I guess in other words, how important is eval compared to the browser-specific features?

**Comment by LiCybora** [comment]
`eval` can run whatever script you want. That's why Mozilla think calling `eval` with unknown web content is dangerous. For browser-specific features, Firefox can edit any incoming response data so it is possible to remove those codes with adblock detecting before you browser run it, but I am not sure whether it is good to use before Mozilla resolve #108 (issue almost for a year). You may also take a look of links in README for further information.

I cannot decide which one you should use. At least for now, they differ by only one rule, and I may re-implement the disabled rule with other allowed methods in future, aiming not to differ their performance.

**Comment by shmediaproductions** [comment]
Cool thanks for the detailed response. I think I'll just stick with the auto updates
