### ISSUE TITLE
Experimental Rules?

### ISSUE THREAD

**Issue by RicoHeat** [LiCybora/NanoDefenderFirefox#184]
PLEASE FIRST READ THIS:
https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue
-->
### Environment (Required):

- Operating System and Version: 
- Browser and Version: 
- Adblocker and Version: 
- Nano Defender Version: 

### Add everything else that you believe to be useful below (optional):
Please explain what happens when enabling experimental rules on Nano Defender Firefox.. Or maybe add a (info) icon next to the check box explaining.. `Thanks!`

**Comment by LiCybora** [comment]
Originally, experimental rules are used to deal with sites that require to use Firefox specific API to deal with (so the upstream Chrome version do not have them). But now they are just some rules that someone reported works while someone not. Upstream decide to remove at all but I move to experimental for user choose whether to use before other solutions out.

However, due to lack of time and feedback, those rules are not updated for long and cannot sure it is 100% working. Nothing will happen if you do not browse any site inside the `debug.js`.
