### ISSUE TITLE
Availability on AMO

### ISSUE THREAD

**Issue by rayman89** [LiCybora/NanoDefenderFirefox#23]
Sorry if this is not the appropriate place to ask this but why is the addon unlisted on AMO?

**Comment by LiCybora** [comment]
Because Mozilla policy of forbidding assignment of innerHTML and custom DOM library. Changing them is not an easy task as many sites are affected and some with Geo Lock or require account. It will be hard for me to ensure my changes would not affect users. Also deprecating the current DOM library might cause 20 times slower for launch.

This product was on AMO before, but removed by Mozilla due to the above reason. In the past day I tried to replace DOM library with jQuery and use alternative method for innerHTML, but I regret this decision after the need of testing affected sites. Some domains itself looks good but may not be the same story when embedded into other sites, such as video streaming service with anti-adblocking. Therefore I decide to keep it unlisted to make my life easier.

But it is welcomed if there are volunteers willing to participate. Just mark the changes and show some screenshot for relevant site to verify. Then I may re-consider for let it up on AMO. However, inform jspenguin2017 first if anyone really want to perform this job, as he is the owner and developer of this product and he knows much more than me.

Reference:
https://github.com/NanoAdblocker/NanoCore/issues/41#issuecomment-364144608
https://www.reddit.com/r/firefox/comments/8e8re8/why_dont_more_people_use_firefox/e0dtnnl/

**Comment by rayman89** [comment]
Thank you for the explanation.  I know nothing about coding so this might sound stupid but would it be possible to put the prohibited content on for example a userscript or something complementary that the user has to add after installing the addon? If that's possible it would be nice so that less experienced users are able to use this addon and get to know of it's existence. For example I thought the addon was dead because it was not on AMO anymore and AAK cont was discontinued.

**Comment by jspenguin2017** [comment]
Anti-adblock system like this cannot be implemented as an Userscript, that is why I rewrote 5k+ lines of code twice to make it a WebExtension. Modern Userscript hosts have really bad race conditions that cause a lot of problems. 

For switching `libdom` to jQuery, you need to rewrite all 5000+ likes of content rules, as `libdom` was not designed to be compatible with jQuery and is fundamentally different than jQuery. I am unhappy about how jQuery works, it is an insanely bloated library and it's too late for them to change, so good luck on replacing `libdom`.

**Comment by icl7126** [comment]
Hello @LiCybora ,
I've started a discussion also on Discourse Mozilla:
https://discourse.mozilla.org/t/get-nano-defender-for-firefox-add-on-to-amo/31214

It's a friendly forum for add-on developers with a lot of skilled people.

**Comment by jspenguin2017** [comment]
> Note: The foregoing assumes that html does not contain its own body tag. I assume that’s true in the context of this extension.

That is not a safe assumption. 

-----

```
  while (j>0){
    s.appendChild(htdoc.body.childNodes[0]); 
    j--;
  }
```

Why not just: 
```
  while (j--)
    s.appendChild(htdoc.body.childNodes[0]); 
```

**Comment by TonyTough** [comment]
I noticed, that the link
Get Nano Defender for Firefox (Unlisted, Beta, Maintained by @LiCybora)

has been removed from the Nano Defender homepage
https://jspenguin2017.github.io/uBlockProtector/

Is there a specific reason for this?

**Comment by jspenguin2017** [comment]
@TonyTough I noticed that the port was taking over 5 days to pull changes, and I wan't sure whether the port is still active. If @LiCybora can confirm that he is back again, I will put the link back up.

**Comment by LiCybora** [comment]
@jspenguin2017 Yes I am here. Sorry for being busy to update in two weeks ago. I apologize for any inconvenience.

**Comment by LiCybora** [comment]
Hello guys, I changed my mind recently. I try my best to patch all innerHTML assignment, although it is just a workaround...

Rewriting libdom...well, I changed the namespace in order not to treat as jquery syntax to bypass the auto-reviewer. Actually I cannot find any policy about forbidding self-written library, let's rethink about it if they ban again.

I update my code in [another branch](https://github.com/LiCybora/NanoDefenderFirefox/tree/moz), who are interested can review and feedback. If everything looks good, I plan to let it available on AMO in upcoming version.

**Comment by ScottRFrost** [comment]
Nano Defender itself doesn't appear to be available in AMO anymore.  Are you planning on porting that from upstream as well, or should we just consider this extension to be used with uBlock Origin on Firefox?

**Comment by LiCybora** [comment]
> Nano Defender itself doesn't appear to be available in AMO anymore.

As of the time writing this comment, Nano Defender still on AMO and what do you mean not appear?

>  used with uBlock Origin on Firefox

I guess you mean Nano Adblocker not appear in AMO right? If yes then yes I have plan in porting, but I need permission granted by upstream and I still need some preparation. You can find my repository and unofficial build [here](https://github.com/LiCybora/NanoCoreFirefox). Before I settle down, use uBO for now, or if you want help debugging for me, download that unofficial build and report issue to me.

**Comment by jspenguin2017** [comment]
@LiCybora You can publish it when you think it's stable enough. As for the integration between NA and ND, you can't really implement that before publishing, and chances are it's just 2 lines of code change.

**Comment by LiCybora** [comment]
Done. Now is online: https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker-firefox/

Also ND need to update for integration working. I will edit all the README soon.

To take care old user who install and forget, GitHub host will still keep update for a while, although it is recommend migrating to AMO version ASAP.

**Comment by jspenguin2017** [comment]
OK. Let me know when you have the integration sorted out. I'll link it in my README.

**Comment by LiCybora** [comment]
Both NA and ND on AMO can now integrated. However, installing one from AMO and one from GitHub will not be integrated and I do not expected user do so.

**Comment by ExE-Boss** [comment]
As for the extension&nbsp;ID, is&nbsp;it&nbsp;the&nbsp;same one as&nbsp;from @jspenguin2017’s release from two&#x2011;ish years ago, or&nbsp;is&nbsp;it&nbsp;a&nbsp;different extension&nbsp;ID?

**Comment by LiCybora** [comment]
Different ID. I cannot reuse the one from him without login his account. You will need to reconfigure those settings. Luckily, you can backup settings to file and import to new extension and restore easily.

**Comment by jspenguin2017** [comment]
Alright, when you are ready, let me know which README to link. Thanks for your contribution.

**Comment by LiCybora** [comment]
This one as homepage https://github.com/LiCybora/NanoCoreFirefox

**Comment by jspenguin2017** [comment]
OK. Looks good.

**Comment by LiCybora** [comment]
Since both extensions are online now, this issue will be closed. I really hope this issue never need to reopen... If any issue other than not found on AMO, please feel free to open a new issue.

I will remove the "experimental" state near the end of this month, as nothing is actually experimenting now.

The GitHub host will still receive update for care old user at least for now, but it will likely strict follow upstream and not receive any platform-specified update (such as disable console). Users are encouraged migrating to AMO and remove the GitHub version ASAP (remember backup you Nano Adblocker first if you use it before).

Waterfox users, although is not supported browser, are however discourage moving to AMO due to lack of dynamic content script API (need FF 59+) which can totally stop ND functioning. They should mod based on the GitHub version/Chromium one if they really want to and accept any risks.

Finally, thanks for everyone support and contribute for this Firefox port.
