### ISSUE TITLE
check for update

### ISSUE THREAD

**Issue by srouquette** [LiCybora/NanoDefenderFirefox#25]
Would it be possible to provide a "check for update" which would automatically check the github release, if we have to manually update the extension?

Right now, I usually forget to update the extension until I remember to (maybe once a month).

Since the extension isn't on the mozilla store, it would help.

**Comment by LiCybora** [comment]
By default, Firefox will automatically check update for you everyday (86400 secs), unless `Update addons automatically` is unchecked. If you don't want Firefox auto-update all addons, you may just leave that option uncheck but set Nano Defender automatically update on instead of default. If you are unhappy with the default auto-update checking interval, you can change in `about:config` and `extensions.update.interval`. You may also go `about:addons` and click `Check for updates` manually without going GitHub.

**Comment by sylvain-rouquette** [comment]
ok, I didn't know that it was already working by default.
