### ISSUE TITLE
IS this official?

### ISSUE THREAD

**Issue by rayman89** [LiCybora/NanoDefenderFirefox#67]
I just found this on AMO uploaded by Fiore https://addons.mozilla.org/en-US/firefox/addon/nanodefender/ is that the real thing or is it a fork or a scam?

**Comment by jspenguin2017** [comment]
It's not official, although I can't say that is it malicious. Use at your own risk, there will be absolutely no support from official developers if you run into troubles.

**Comment by LiCybora** [comment]
The given link is **NOT official** and the account is **NOT** mine, neither adblocker nor defender. I cannot say whether they are evil. From quick code review, they are just almost the exact Chromium version code but submit to AMO (both Adblocker and Defender).

Thus, their integration may fail, because the extension ID identification (i mean between defender and adblocker) don't even mod. I recommend against using them as those incomplete mod probably goes wrong, and we give no support for them.

**Comment by Puremin0rez** [comment]
Is there any chance you'd be willing to put Nano Defender on the Firefox Addons site? It'd be nice to easily find, and get auto updates. Currently I believe there are no auto updates and we must update manually from the releases page, right?

**Comment by rayman89** [comment]
@Puremin0rez It does auto update. It does not need to be from AMO to auto update.

**Comment by LiCybora** [comment]
AMO pulled that down and the link no longer works, things just over. Just remind that official ND will not exist on AMO unless you see any announcement on the official page.

**Comment by jspenguin2017** [comment]
It's up again.
